version: '3'

services:
  main-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    volumes:
      - ./backend:/app

  debug-app:
    build:
      context: ./backend
      dockerfile: Dockerfile.debug
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app_debug.py
    volumes:
      - ./backend:/app
