services:
  - type: web
    name: censorly-backend
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      cd backend
      pip install --upgrade pip
      pip install -r requirements.txt
      echo "Testing app import..."
      python -c "from app_supabase import app; print('✅ Build verification successful')"
    startCommand: |
      cd backend
      python run_production.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.18
    healthCheckPath: /health