services:
  # Main service
  - type: web
    name: censorly-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.13
    healthCheckPath: /health
    autoDeploy: false
    
  # Debug service (lightweight version for troubleshooting)
  - type: web
    name: censorly-debug
    env: python
    buildCommand: cd backend && pip install -r requirements-debug.txt
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT app_debug:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.13
    healthCheckPath: /health
    autoDeploy: false
