services:
  - type: web
    name: censorly-backend
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health