web: gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 300 "app:create_app()"
worker: celery -A services.celery_worker.celery worker --loglevel=info --concurrency=2
beat: celery -A services.celery_worker.celery beat --loglevel=info
